// flexible-graphrag-ui/frontend-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  standalone: false
})
export class AppComponent {
  title = 'Flexible GraphRAG (Angular)';
  
  onFolderProcessed(event: { path: string }): void {
    console.log('Folder was processed:', event.path);
    // You can add any additional logic here when a folder is processed
  }
}

<div class="app-container">
  <mat-toolbar color="primary">
    <mat-toolbar-row>
      <span>{{ title }}</span>
      <span class="spacer"></span>
    </mat-toolbar-row>
  </mat-toolbar>

  <main class="main-content">
    <div class="container">
      <div class="header">
        <h1></h1>
        <p class="subtitle"></p>
      </div>

      <div class="content">
        <app-process-folder (processed)="onFolderProcessed($event)"></app-process-folder>
        <app-query-form></app-query-form>
      </div>
    </div>
  </main>
</div>

// flexible-graphrag-ui/frontend-vue/src/App.vue
<template>
  <v-app>
    <v-app-bar app color="primary" dark>
      <v-toolbar-title>Flexible GraphRAG (Vue)</v-toolbar-title>
    </v-app-bar>

    <v-main>
      <v-container class="py-8">
        <process-folder @processed="onFolderProcessed" />
        <query-form />
      </v-container>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import ProcessFolder from './components/ProcessFolder.vue';
import QueryForm from './components/QueryForm.vue';

export default defineComponent({
  name: 'App',
  components: {
    ProcessFolder,
    QueryForm,
  },
  methods: {
    onFolderProcessed(event: { path: string }) {
      console.log('Folder was processed:', event.path);
      // You can add any additional logic here when a folder is processed
    }
  }
});
</script>

<style>
@import 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap';
</style>
