// flexible-graphrag-ui/frontend-angular/src/app/components/process-folder/process-folder.component.ts
import { Component, EventEmitter, Output, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatSnackBar } from '@angular/material/snack-bar';
import { finalize, switchMap, takeWhile, takeUntil } from 'rxjs/operators';
import { Subject, interval } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { EnvService } from '../../services/env.service';
import { AsyncProcessingResponse, ProcessingStatusResponse } from '../../models/api.models';

@Component({
  selector: 'app-process-folder',
  templateUrl: './process-folder.component.html',
  styleUrls: ['./process-folder.component.scss'],
  standalone: false
})
export class ProcessFolderComponent implements OnInit, OnDestroy {
  @Output() processed = new EventEmitter<{ dataSource: string, path?: string }>();
  
  form: FormGroup;
  isProcessing = false;
  processingStatus = '';
  processingProgress = 0;
  currentProcessingId: string | null = null;
  statusData: any = null;
  
  // In-window messages instead of popups
  successMessage = '';
  errorMessage = '';
  
  private destroy$ = new Subject<void>();

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService,
    private snackBar: MatSnackBar,
    private envService: EnvService
  ) {
    this.form = this.fb.group({
      dataSource: ['filesystem', Validators.required],
      folderPath: [''],
      // CMIS fields
      cmisUrl: ['http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom'],
      cmisUsername: ['admin'],
      cmisPassword: ['admin'],
      // Alfresco fields
      alfrescoUrl: ['http://localhost:8080/alfresco'],
      alfrescoUsername: ['admin'],
      alfrescoPassword: ['admin']
    });

    // Set up conditional validators
    this.form.get('dataSource')?.valueChanges.subscribe(dataSource => {
      this.updateValidators(dataSource);
    });
  }

  ngOnInit(): void {
    // Set default folder path from environment config
    const defaultPath = this.envService.defaultFolderPath;
    if (defaultPath) {
      this.form.patchValue({
        folderPath: defaultPath
      });
    }
    
    // Set initial validators
    this.updateValidators('filesystem');
  }

  private updateValidators(dataSource: string): void {
    // Clear all validators first
    Object.keys(this.form.controls).forEach(key => {
      if (key !== 'dataSource') {
        this.form.get(key)?.clearValidators();
      }
    });

    // Set validators based on data source
    switch (dataSource) {
      case 'filesystem':
        this.form.get('folderPath')?.setValidators([Validators.required]);
        break;
      case 'cmis':
        this.form.get('cmisUrl')?.setValidators([Validators.required]);
        this.form.get('cmisUsername')?.setValidators([Validators.required]);
        this.form.get('cmisPassword')?.setValidators([Validators.required]);
        this.form.get('folderPath')?.setValidators([Validators.required]);
        break;
      case 'alfresco':
        this.form.get('alfrescoUrl')?.setValidators([Validators.required]);
        this.form.get('alfrescoUsername')?.setValidators([Validators.required]);
        this.form.get('alfrescoPassword')?.setValidators([Validators.required]);
        this.form.get('folderPath')?.setValidators([Validators.required]);
        break;
    }

    // Update validity
    Object.keys(this.form.controls).forEach(key => {
      this.form.get(key)?.updateValueAndValidity();
    });
  }

  onSubmit(): void {
    if (this.form.invalid || this.isProcessing) {
      return;
    }

    this.isProcessing = true;
    const formValue = this.form.value;
    
    // Build request based on data source
    const request: any = {
      data_source: formValue.dataSource
    };

    if (formValue.dataSource === 'filesystem') {
      request.paths = [formValue.folderPath];
    } else if (formValue.dataSource === 'cmis') {
      // For now, we'll pass the paths as the folder path since CMIS isn't fully implemented
      request.paths = [formValue.folderPath];
      // In future, these would be used to configure CMIS connection
      request.cmis_config = {
        url: formValue.cmisUrl,
        username: formValue.cmisUsername,
        password: formValue.cmisPassword,
        folder_path: formValue.folderPath
      };
    } else if (formValue.dataSource === 'alfresco') {
      // For now, we'll pass the paths as the folder path since Alfresco isn't fully implemented
      request.paths = [formValue.folderPath];
      // In future, these would be used to configure Alfresco connection
      request.alfresco_config = {
        url: formValue.alfrescoUrl,
        username: formValue.alfrescoUsername,
        password: formValue.alfrescoPassword,
        path: formValue.folderPath
      };
    }

    this.apiService.ingestDocuments(request)
      .subscribe({
        next: (response: AsyncProcessingResponse) => {
          if (response.status === 'started') {
            this.processingStatus = response.message;
            this.processingProgress = 0;
            this.currentProcessingId = response.processing_id;
            
            // Show success message in-window instead of popup
            this.successMessage = `Processing started: ${response.estimated_time || 'Please wait...'}`;
            this.errorMessage = '';
            
            this.pollProcessingStatus(response.processing_id, formValue);
          } else if (response.status === 'completed') {
            this.handleProcessingComplete(formValue);
          } else if (response.status === 'failed') {
            this.handleProcessingError(response.error || 'Processing failed');
          }
        },
        error: (error) => {
          this.handleProcessingError(error.message || 'Error starting document processing');
        }
      });
  }

  private pollProcessingStatus(processingId: string, formValue: any): void {
    // Poll every 2 seconds
    interval(2000)
      .pipe(
        switchMap(() => this.apiService.getProcessingStatus(processingId)),
        takeWhile((status: ProcessingStatusResponse) => 
          status.status === 'started' || status.status === 'processing', true
        ),
        takeUntil(this.destroy$)
      )
      .subscribe({
        next: (status: ProcessingStatusResponse) => {
          this.processingStatus = status.message;
          this.processingProgress = status.progress;
          this.statusData = status;  // Store full status for enhanced progress display
          
          // Clear initial "processing started" message once real progress updates begin
          if (this.successMessage.startsWith('Processing started:') && status.progress > 0) {
            this.successMessage = '';
          }
          
          if (status.status === 'completed') {
            this.handleProcessingComplete(formValue);
          } else if (status.status === 'failed') {
            this.handleProcessingError(status.error || 'Processing failed');
          } else if (status.status === 'cancelled') {
            this.handleProcessingCancelled();
          }
        },
        error: (error: any) => {
          this.handleProcessingError('Error checking processing status: ' + error.message);
        }
      });
  }

  private handleProcessingComplete(formValue: any): void {
    this.isProcessing = false;
    this.processingStatus = '';
    this.processingProgress = 0;
    this.currentProcessingId = null;
    
    // Show success message in-window instead of popup
    this.successMessage = 'Documents ingested successfully!';
    this.errorMessage = '';
    
    this.processed.emit({ 
      dataSource: formValue.dataSource, 
      path: formValue.folderPath 
    });
  }

  private handleProcessingError(errorMessage: string): void {
    this.isProcessing = false;
    this.processingStatus = '';
    this.processingProgress = 0;
    this.currentProcessingId = null;
    
    // Show error message in-window instead of popup
    this.errorMessage = errorMessage;
    this.successMessage = '';
  }

  private handleProcessingCancelled(): void {
    this.isProcessing = false;
    this.processingStatus = '';
    this.processingProgress = 0;
    this.currentProcessingId = null;
    
    // Show cancellation message in-window with auto-clear
    this.successMessage = 'Processing cancelled successfully';
    this.errorMessage = '';
    
    // Auto-clear the cancellation message after 5 seconds
    setTimeout(() => {
      if (this.successMessage === 'Processing cancelled successfully') {
        this.successMessage = '';
      }
    }, 5000);
  }

  cancelProcessing(): void {
    if (!this.currentProcessingId) return;
    
    this.apiService.cancelProcessing(this.currentProcessingId).subscribe({
      next: (response: any) => {
        if (response.success) {
          // Success will be handled by the polling status check
        } else {
          this.errorMessage = 'Failed to cancel processing';
          this.successMessage = '';
        }
      },
      error: (error: any) => {
        console.error('Error cancelling processing:', error);
        this.errorMessage = 'Error cancelling processing';
        this.successMessage = '';
      }
    });
  }

  getFileName(filePath: string): string {
    return filePath.split(/[/\\]/).pop() || filePath;
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<mat-card class="mb-4">
  <mat-card-header>
    <mat-card-title>Ingest Documents</mat-card-title>
    <mat-card-subtitle>Ingest documents from various data sources</mat-card-subtitle>
  </mat-card-header>
  
  <mat-card-content>
    <form [formGroup]="form" (ngSubmit)="onSubmit()">
      <!-- Data Source Selection -->
      <mat-form-field appearance="outline" class="w-100 mb-3">
        <mat-label>Data Source</mat-label>
        <mat-select formControlName="dataSource" [disabled]="isProcessing">
          <mat-option value="filesystem">File System</mat-option>
          <mat-option value="cmis">CMIS Repository</mat-option>
          <mat-option value="alfresco">Alfresco Repository</mat-option>
        </mat-select>
        <mat-hint>Choose the data source for document ingestion</mat-hint>
      </mat-form-field>

      <!-- File System Path Input -->
      <mat-form-field appearance="outline" class="w-100" *ngIf="form.value.dataSource === 'filesystem'">
        <mat-label>File or Folder Path</mat-label>
        <input 
          matInput 
          formControlName="folderPath"
          placeholder="Enter file or folder path"
          [disabled]="isProcessing"
        >
        <mat-hint>Enter the path to a file or folder you want to process</mat-hint>
      </mat-form-field>

      <!-- CMIS Configuration -->
      <div *ngIf="form.value.dataSource === 'cmis'" class="cmis-config">
        <mat-form-field appearance="outline" class="w-100 mb-2">
          <mat-label>CMIS Repository URL</mat-label>
          <input 
            matInput 
            formControlName="cmisUrl"
            placeholder="http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom"
            [disabled]="isProcessing"
          >
        </mat-form-field>
        
        <div class="row">
          <div class="col-md-6">
            <mat-form-field appearance="outline" class="w-100 mb-2">
              <mat-label>Username</mat-label>
              <input 
                matInput 
                formControlName="cmisUsername"
                placeholder="Enter CMIS username"
                [disabled]="isProcessing"
              >
            </mat-form-field>
          </div>
          <div class="col-md-6">
            <mat-form-field appearance="outline" class="w-100 mb-2">
              <mat-label>Password</mat-label>
              <input 
                matInput 
                type="password"
                formControlName="cmisPassword"
                placeholder="Enter CMIS password"
                [disabled]="isProcessing"
              >
            </mat-form-field>
          </div>
        </div>
        
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Folder Path</mat-label>
          <input 
            matInput 
            formControlName="folderPath"
            placeholder="/Sites/example-site/documentLibrary"
            [disabled]="isProcessing"
          >
          <mat-hint>CMIS folder path to process</mat-hint>
        </mat-form-field>
      </div>

      <!-- Alfresco Configuration -->
      <div *ngIf="form.value.dataSource === 'alfresco'" class="alfresco-config">
        <mat-form-field appearance="outline" class="w-100 mb-2">
          <mat-label>Alfresco Base URL</mat-label>
          <input 
            matInput 
            formControlName="alfrescoUrl"
            placeholder="http://localhost:8080/alfresco"
            [disabled]="isProcessing"
          >
        </mat-form-field>
        
        <div class="row">
          <div class="col-md-6">
            <mat-form-field appearance="outline" class="w-100 mb-2">
              <mat-label>Username</mat-label>
              <input 
                matInput 
                formControlName="alfrescoUsername"
                placeholder="Enter Alfresco username"
                [disabled]="isProcessing"
              >
            </mat-form-field>
          </div>
          <div class="col-md-6">
            <mat-form-field appearance="outline" class="w-100 mb-2">
              <mat-label>Password</mat-label>
              <input 
                matInput 
                type="password"
                formControlName="alfrescoPassword"
                placeholder="Enter Alfresco password"
                [disabled]="isProcessing"
              >
            </mat-form-field>
          </div>
        </div>
        
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Path</mat-label>
          <input 
            matInput 
            formControlName="folderPath"
            placeholder="/Sites/example-site/documentLibrary"
            [disabled]="isProcessing"
          >
          <mat-hint>Alfresco path to process</mat-hint>
        </mat-form-field>
      </div>

      <!-- Processing Status -->
      <div *ngIf="isProcessing" class="processing-status mt-3 mb-3">
        <div class="d-flex align-items-center mb-2">
          <mat-spinner diameter="20" class="me-2"></mat-spinner>
          <span class="status-text">{{ processingStatus || 'Processing documents...' }}</span>
        </div>
        <mat-progress-bar 
          mode="determinate" 
          [value]="processingProgress"
          class="progress-bar"
        ></mat-progress-bar>
        <small class="progress-text">
          {{ processingProgress }}% complete
          <div *ngIf="statusData?.file_progress" class="mt-1">
            {{ statusData.file_progress }}
          </div>
          <div *ngIf="statusData?.current_file" class="mt-1">
            Processing: {{ getFileName(statusData.current_file) }}
          </div>
          <div *ngIf="statusData?.current_phase" class="mt-1">
            Phase: {{ statusData.current_phase }}
          </div>
          <div *ngIf="statusData?.estimated_time_remaining" class="mt-1">
            Time remaining: {{ statusData.estimated_time_remaining }}
          </div>
        </small>
        <button 
          type="button"
          mat-stroked-button 
          color="warn" 
          (click)="cancelProcessing()"
          class="cancel-btn mt-2"
          [disabled]="!currentProcessingId"
        >
          Cancel Processing
        </button>
      </div>

      <!-- Success Message -->
      <div *ngIf="successMessage" class="alert alert-success alert-dismissible mt-3">
        {{ successMessage }}
        <button type="button" class="btn-close" aria-label="Close" (click)="successMessage = ''"></button>
      </div>

      <!-- Error Message -->
      <div *ngIf="errorMessage" class="alert alert-danger alert-dismissible mt-3">
        {{ errorMessage }}
        <button type="button" class="btn-close" aria-label="Close" (click)="errorMessage = ''"></button>
      </div>

      <div class="mt-3">
        <button 
          mat-raised-button 
          color="primary" 
          type="submit"
          [disabled]="form.invalid || isProcessing"
        >
          <span *ngIf="!isProcessing">Ingest Documents</span>
          <span *ngIf="isProcessing">Processing...</span>
        </button>
      </div>
    </form>
  </mat-card-content>
</mat-card>

// flexible-graphrag-ui/frontend-vue/src/components/ProcessFolder.vue
<template>
  <v-card class="pa-4 mb-4">
    <v-card-title>Process Documents</v-card-title>
    <v-card-text>
      <!-- Data Source Selection -->
      <v-select
        v-model="dataSource"
        :items="dataSourceOptions"
        label="Data Source"
        variant="outlined"
        class="mb-4"
        :disabled="isProcessing"
      ></v-select>

      <!-- File System Fields -->
      <template v-if="dataSource === 'filesystem'">
        <v-text-field
          v-model="folderPath"
          label="Folder Path (file or directory)"
          variant="outlined"
          :disabled="isProcessing"
          class="mb-4"
          placeholder="e.g., C:\Documents\reports or /home/user/docs/report.pdf"
        ></v-text-field>
      </template>

      <!-- CMIS Fields -->
      <template v-if="dataSource === 'cmis'">
        <v-text-field
          v-model="cmisUrl"
          label="CMIS Repository URL"
          variant="outlined"
          :disabled="isProcessing"
          class="mb-4"
          placeholder="e.g., http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom"
        ></v-text-field>
        <v-row>
          <v-col cols="6">
            <v-text-field
              v-model="cmisUsername"
              label="Username"
              variant="outlined"
              :disabled="isProcessing"
              class="mb-4"
            ></v-text-field>
          </v-col>
          <v-col cols="6">
            <v-text-field
              v-model="cmisPassword"
              label="Password"
              type="password"
              variant="outlined"
              :disabled="isProcessing"
              class="mb-4"
            ></v-text-field>
          </v-col>
        </v-row>
        <v-text-field
          v-model="folderPath"
          label="Folder Path"
          variant="outlined"
          :disabled="isProcessing"
          class="mb-4"
          placeholder="e.g., /Sites/example/documentLibrary"
        ></v-text-field>
      </template>

      <!-- Alfresco Fields -->
      <template v-if="dataSource === 'alfresco'">
        <v-text-field
          v-model="alfrescoUrl"
          label="Alfresco Base URL"
          variant="outlined"
          :disabled="isProcessing"
          class="mb-4"
          placeholder="e.g., http://localhost:8080/alfresco"
        ></v-text-field>
        <v-row>
          <v-col cols="6">
            <v-text-field
              v-model="alfrescoUsername"
              label="Username"
              variant="outlined"
              :disabled="isProcessing"
              class="mb-4"
            ></v-text-field>
          </v-col>
          <v-col cols="6">
            <v-text-field
              v-model="alfrescoPassword"
              label="Password"
              type="password"
              variant="outlined"
              :disabled="isProcessing"
              class="mb-4"
            ></v-text-field>
          </v-col>
        </v-row>
        <v-text-field
          v-model="folderPath"
          label="Path"
          variant="outlined"
          :disabled="isProcessing"
          class="mb-4"
          placeholder="e.g., /Sites/example/documentLibrary"
        ></v-text-field>
      </template>

      <!-- Processing Status -->
      <template v-if="isProcessing">
        <v-card
          color="info"
          variant="tonal"
          class="mb-4"
        >
          <v-card-text>
            <div class="d-flex align-center mb-2">
              <v-progress-circular
                indeterminate
                size="20"
                class="me-2"
              ></v-progress-circular>
              <span>{{ processingStatus || 'Processing documents...' }}</span>
            </div>
            <v-progress-linear
              :model-value="processingProgress"
              height="8"
              rounded
              color="primary"
              class="mb-2"
            ></v-progress-linear>
            <div class="text-caption text-medium-emphasis">
              {{ processingProgress }}% complete
              <div v-if="statusData?.file_progress" class="mt-1">
                {{ statusData.file_progress }}
              </div>
              <div v-if="statusData?.current_file" class="mt-1">
                Processing: {{ getFileName(statusData.current_file) }}
              </div>
              <div v-if="statusData?.current_phase" class="mt-1">
                Phase: {{ statusData.current_phase }}
              </div>
              <div v-if="statusData?.estimated_time_remaining" class="mt-1">
                Time remaining: {{ statusData.estimated_time_remaining }}
              </div>
            </div>
            <v-btn
              variant="outlined"
              color="error"
              size="small"
              @click="cancelProcessing"
              class="mt-2"
            >
              Cancel Processing
            </v-btn>
          </v-card-text>
        </v-card>
      </template>

      <v-btn
        color="primary"
        @click="handleProcessFolder"
        :disabled="!isFormValid || isProcessing"
        :loading="isProcessing"
        size="large"
      >
        {{ isProcessing ? 'Processing...' : 'Ingest Documents' }}
      </v-btn>

      <v-alert
        v-if="error"
        type="error"
        class="mt-4"
      >
        {{ error }}
      </v-alert>

      <v-alert
        v-if="success"
        type="success"
        class="mt-4"
      >
        {{ success }}
      </v-alert>
    </v-card-text>
  </v-card>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import axios from 'axios';
import { IngestRequest, AsyncProcessingResponse, ProcessingStatusResponse } from '../types/api';

const emit = defineEmits<{
  (e: 'processed', payload: { dataSource: string, path?: string }): void;
}>();

// Get folder path from environment variables or use default
const defaultFolderPath = import.meta.env.VITE_PROCESS_FOLDER_PATH || '/Shared/GraphRAG';

// Data source options
const dataSourceOptions = [
  { title: 'File System', value: 'filesystem' },
  { title: 'CMIS Repository', value: 'cmis' },
  { title: 'Alfresco Repository', value: 'alfresco' }
];

// Define reactive variables
const dataSource = ref('filesystem');
const folderPath = ref(defaultFolderPath);

// CMIS fields
const cmisUrl = ref('http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom');
const cmisUsername = ref('admin');
const cmisPassword = ref('admin');

// Alfresco fields
const alfrescoUrl = ref('http://localhost:8080/alfresco');
const alfrescoUsername = ref('admin');
const alfrescoPassword = ref('admin');

// UI state
const isProcessing = ref(false);
const error = ref('');
const success = ref('');
const processingStatus = ref('');
const processingProgress = ref(0);
const currentProcessingId = ref<string | null>(null);
const statusData = ref<any>(null);

// Computed property for form validation
const isFormValid = computed(() => {
  switch (dataSource.value) {
    case 'filesystem':
      return folderPath.value.trim() !== '';
    case 'cmis':
      return folderPath.value.trim() !== '' && 
             cmisUrl.value.trim() !== '' && 
             cmisUsername.value.trim() !== '' && 
             cmisPassword.value.trim() !== '';
    case 'alfresco':
      return folderPath.value.trim() !== '' && 
             alfrescoUrl.value.trim() !== '' && 
             alfrescoUsername.value.trim() !== '' && 
             alfrescoPassword.value.trim() !== '';
    default:
      return false;
  }
});

// Clear messages when data source changes
watch(dataSource, () => {
  error.value = '';
  success.value = '';
  processingStatus.value = '';
  processingProgress.value = 0;
});

// Helper function to extract filename from path
const getFileName = (filePath: string): string => {
  return filePath.split(/[/\\]/).pop() || filePath;
};

// Polling function for processing status
const pollProcessingStatus = async (processingId: string): Promise<void> => {
  try {
    const response = await axios.get<ProcessingStatusResponse>(`/api/processing-status/${processingId}`);
    const status = response.data;
    
    processingStatus.value = status.message;
    processingProgress.value = status.progress;
    statusData.value = status;  // Store full status for enhanced progress display
    
    if (status.status === 'completed') {
      isProcessing.value = false;
      processingStatus.value = '';
      processingProgress.value = 0;
      currentProcessingId.value = null;
      success.value = 'Documents ingested successfully!';
      emit('processed', { 
        dataSource: dataSource.value, 
        path: folderPath.value 
      });
    } else if (status.status === 'failed') {
      isProcessing.value = false;
      processingStatus.value = '';
      processingProgress.value = 0;
      currentProcessingId.value = null;
      error.value = status.error || 'Processing failed';
    } else if (status.status === 'cancelled') {
      isProcessing.value = false;
      processingStatus.value = '';
      processingProgress.value = 0;
      currentProcessingId.value = null;
      success.value = 'Processing cancelled successfully';
    } else if (status.status === 'started' || status.status === 'processing') {
      // Continue polling
      setTimeout(() => pollProcessingStatus(processingId), 2000);
    }
  } catch (err: any) {
    console.error('Error checking processing status:', err);
    error.value = 'Error checking processing status';
    isProcessing.value = false;
    currentProcessingId.value = null;
  }
};

const processFolder = async (): Promise<boolean> => {
  if (!isFormValid.value || isProcessing.value) return false;
  
  try {
    isProcessing.value = true;
    error.value = '';
    success.value = '';
    
    console.log('Sending request to process documents with data source:', dataSource.value);
    
    const request: IngestRequest = {
      data_source: dataSource.value
    };

    if (dataSource.value === 'filesystem') {
      request.paths = [folderPath.value];
    } else if (dataSource.value === 'cmis') {
      request.paths = [folderPath.value];
      request.cmis_config = {
        url: cmisUrl.value,
        username: cmisUsername.value,
        password: cmisPassword.value,
        folder_path: folderPath.value
      };
    } else if (dataSource.value === 'alfresco') {
      request.paths = [folderPath.value];
      request.alfresco_config = {
        url: alfrescoUrl.value,
        username: alfrescoUsername.value,
        password: alfrescoPassword.value,
        path: folderPath.value
      };
    }
    
    const response = await axios.post<AsyncProcessingResponse>('/api/ingest', request, {
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      }
    });
    
    console.log('Response received:', response);
    
    // Handle async processing response
    if (response.data.status === 'started') {
      processingStatus.value = response.data.message;
      processingProgress.value = 0;
      currentProcessingId.value = response.data.processing_id;
      success.value = `Processing started: ${response.data.estimated_time || 'Please wait...'}`;
      // Start polling for status
      setTimeout(() => pollProcessingStatus(response.data.processing_id), 2000);
      return true;
    } else if (response.data.status === 'completed') {
      success.value = 'Documents ingested successfully!';
      emit('processed', { 
        dataSource: dataSource.value, 
        path: folderPath.value 
      });
      return true;
    } else if (response.data.status === 'failed') {
      error.value = response.data.error || 'Processing failed';
      return false;
    } else {
      error.value = response.data.error || 'Unknown processing status';
      return false;
    }
  } catch (err: any) {
    console.error('Error processing documents:', {
      message: err.message,
      response: err.response?.data,
      status: err.response?.status,
      headers: err.response?.headers
    });
    error.value = err.response?.data?.detail || err.response?.data?.error || 'Error processing documents';
    isProcessing.value = false;
    currentProcessingId.value = null;
    return false;
  }
};

const cancelProcessing = async (): Promise<void> => {
  if (!currentProcessingId.value) return;
  
  try {
    const response = await axios.post(`/api/cancel-processing/${currentProcessingId.value}`);
    if (response.data.success) {
      success.value = 'Processing cancelled successfully';
      isProcessing.value = false;
      processingStatus.value = '';
      processingProgress.value = 0;
      currentProcessingId.value = null;
    } else {
      error.value = 'Failed to cancel processing';
    }
  } catch (err: any) {
    console.error('Error cancelling processing:', err);
    error.value = 'Error cancelling processing';
  }
};

const handleProcessFolder = (event: Event) => {
  event.preventDefault();
  processFolder();
};
</script>
